version: "3"

services:
  web:
    image: mac/jekyll
    container_name: passepartoutvpn-web
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --watch --force_polling --verbose -H 0.0.0.0 -P 80
    environment:
      VIRTUAL_HOST: passepartoutvpn.wtf

networks:
  default:
    name: nginx-proxy
